#! /bin/sh

sxhkd &
compton &
#polybar example &
~/.config/polybar/launch.sh
~/.fehbg
xrandr -s 1360x768

bspc monitor -d I II III IV

bspc config border_width        2 
bspc config window_gap          10
# bspc config top_padding         26
bspc config normal_border_color "#474644"
bspc config active_border_color "#4E6BA0"
bspc config focused_border_color "#E3B5B4"
bspc config presel_feedback_color "#c7e7f1"

# bspc config automatic_scheme     spiral
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Application Rules
bspc rule -a Geany desktop='^3' follow=on
bspc rule -a Firefox-esr desktop='^2' follow=on
bspc rule -a st-256color desktop='^1' follow=on
