#! /bin/sh

sxhkd &
compton &
#polybar example &
~/.config/polybar/launch.sh
~/.fehbg
xrandr -s 1360x768

bspc monitor -d I II III IV V

bspc config border_width          2
bspc config window_gap            12
bspc config normal_border_color   "#09071e"
bspc config active_border_color   "#B1576E"
bspc config focused_border_color  "#E9142E"
bspc config presel_feedback_color "#D6A36A"

# bspc config automatic_scheme    spiral
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# Application Rules
bspc rule -a st-256color         desktop='^1' follow=on
bspc rule -a firefox             desktop='^2' follow=on
bspc rule -a Chromium            desktop='^3'
bspc rule -a Code                desktop='^3'
bspc rule -a "jetbrains-idea-ce" desktop='^3'
bspc rule -a TelegramDesktop     desktop='^4' 
