#! /bin/sh

sxhkd &
# picom &
~/.config/polybar/launch.sh
~/.fehbg

bspc monitor -d I II III IV V 

bspc config border_width          0
bspc config window_gap            10
bspc config normal_border_color   "#0e0c17"
bspc config active_border_color   "#dcccd2"
bspc config focused_border_color  "#714a65"
bspc config presel_feedback_color "#D6A36A"

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# Application Rules
bspc rule -a st-256color      desktop='^1' follow=on
bspc rule -a firefox          desktop='^2' 
bspc rule -a Firefox-esr      desktop='^2' 
bspc rule -a Code             desktop='^3' 
bspc rule -a TelegramDesktop  desktop='^4'
bspc rule -a Zathura          desktop='^5'
