#! /bin/sh

sxhkd &
picom &
# picom --config ~/.config/picom/picom.conf & 

# polybar example &
~/.config/polybar/launch.sh
~/.fehbg
xrandr -s 1360x768

bspc monitor -d I II III IV V

bspc config border_width          1
bspc config window_gap            12
bspc config normal_border_color   "#50545d"
bspc config active_border_color   "#BE6E8C"
bspc config focused_border_color  "#9763E4"
bspc config presel_feedback_color "#f2e097"

# bspc config automatic_scheme    spiral
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true
bspc config border_radius         6

# Application Rules
bspc rule -a st-256color desktop='^1' follow=on
bspc rule -a Code desktop='^2' 
bspc rule -a Geany desktop='^2' 
bspc rule -a Brave-browser desktop='^3'
bspc rule -a Firefox-esr desktop='^3' 
bspc rule -a TelegramDesktop desktop='^4' 
