#! /bin/sh

sxhkd &
compton &
#polybar example &
~/.config/polybar/launch.sh
~/.fehbg
xrandr -s 1360x768

bspc monitor -d I II III IV

bspc config border_width          3
bspc config window_gap            12
# bspc config top_padding         29
bspc config normal_border_color   "#686B75"
bspc config active_border_color   "#4E6BA0"
bspc config focused_border_color  "#c7c8cc"
bspc config presel_feedback_color "#e1f2f4"

# bspc config automatic_scheme     spiral
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Application Rules
bspc rule -a Brave-browser desktop='^2' follow=on
bspc rule -a Code          desktop='^3' follow=on
bspc rule -a Geany         desktop='^3' follow=on
bspc rule -a Firefox-esr   desktop='^2' follow=on
bspc rule -a st-256color   desktop='^1' follow=on
